services:
  mysql-db:
    image: mysql:8.0.29
    container_name: mysql-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 5
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/sqls/create-sakila-schema.sql:/docker-entrypoint-initdb.d/1_create-sakila-schema.sql
      - ./data/sqls/sakila-data.sql:/docker-entrypoint-initdb.d/2_sakila-data.sql
      - ./data/sqls/create-databases.sql:/docker-entrypoint-initdb.d/3_create-databases.sql
  db-admin:
    image: phpmyadmin:latest
    container_name: mysql-db-admin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
    ports:
      - "8080:80"
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-workbench:
    image: lspipepr/mysql-workbench:version-8.0.28
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy